framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            reports:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/reports'
                options:
                    exchange:
                        name: reports
                        type: direct

        routing:
            App\Bus\Report\ReportCreatedMessage: reports

when@test:
   framework:
       messenger:
           transports:
               async: 'in-memory://'
