# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true


    App\:
        resource: '../src/'

    App\Service\Product\ProductServiceInterface: '@App\Service\Product\ProductService'
    App\Service\User\UserServiceInterface: '@App\Service\User\UserService'
    App\Service\Cart\CartServiceInterface: '@App\Service\Cart\CartService'
    App\Service\Order\OrderServiceInterface: '@App\Service\Order\OrderService'
