# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.reports.dir: '%kernel.project_dir%/var/reports'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\Report\FileReporter: ~

    App\:
        resource: '../src/'
